### ISSUE TITLE
Submodule to covidm version

### ISSUE THREAD

**Issue by seabbs** [cmmid/SA2UK#1]
Hi Carl, 

This just caught my eye whilst I was having a little think about Makefiles - its looking good. 

Is there a reason not to use a submodule for `covidm`? On the face of it seems like it would be nice as it would give you version control for `covidm` without any really costs I am aware of. Might be missing something though.

**Comment by pearsonca** [comment]
Good question - there are a few reasons not to use submodules more
generically, at least one of which applies to my use of covidm: I have it
as a dependency across multiple projects. I have order 10s of analyses that
use the library, and I don't want that many copies floating around
(especially given that the library has a relatively large data blob
associated with it).

There are ways around that (e.g.
https://stackoverflow.com/questions/27379818/git-possible-to-use-same-submodule-working-copy-by-multiple-projects),
but those kinda mess with the point of having a submodule (to be fair, in
the same way that having it as a library-like project do).

There's also a newer feature called a worktree that might be a better way
to approach this. However, I'd much prefer it as a proper R package, and
not have to think as much about dependency management.

**Comment by seabbs** [comment]
Yes I agree having it as a proper package would make all the sense in the world. 

Hmm that work around seems a bit convoluted (it does highlight the issue of needing different versions in difference projects which might be an issue with your current approach as well). 

worktree is new to me. I don't totally see how it can be used to resolve this but I assume that is from not following the docs fully. Anyhoo closing this as just a discussion point. When you wrap this up and it gets published etc it might be nice to switch out to the submodule approach so that the code here is linked to the correct `covidm` version.

**Comment by seabbs** [comment]
There is some sane discussion of this issue here: https://stackoverflow.com/questions/21077493/how-to-use-submodules-publicly-but-symlinks-to-a-single-clone-locally

I like the authors own suggestion: set up to use submodules and say your going to everywhere but then use a symlink locally and never commit that change to git
